### PR TITLE
update chelsa url

### PR DESCRIPTION
**Pull request by tiemvanderdeure**
Someone at CHELSA decided to change the url...

### CODE REVIEW

**Comment by tiemvanderdeure** [comment]
the test fails are something with codecov that I'm not sure how to fix

**Comment by rafaqz** [comment]
I think it needs a token now

**Review by rafaqz — APPROVED** [review]
Why would they do this 😭

(Especially just removing underscores for no reason...)

**Comment by tiemvanderdeure** [comment]
We probably want to release a patch that has this fix but not the upcoming breaking changes

**Pull request merged**
